using Blackbird.Applications.Sdk.Common;
using Blackbird.Applications.Sdk.Common.Files;

namespace Apps.AEM.Models.Requests;

public class GetIdsFromContentRequest
{
    [Display("Content", Description = "Content file generated by Blackbird.")]
    public FileReference File { get; set; } = new();
}
